api/__init__.py
from flask import Flask
from flask_cors import CORS
#from authlib.integrations.flask_client import OAuth
# for oauth

from api.blueprints.main import main_bp
from api.blueprints.admin import admin_bp
from api.blueprints.user import user_bp
from api.blueprints.auth import auth_bp


#from front_end.api.extensions import login_manager
import os

# def create_app(config_name=None):

template_dir = os.path.abspath('./api/templates/')

app = Flask(__name__, static_folder='../build', static_url_path='', template_folder=template_dir)
CORS(app)
#app = Flask('api')

app.secret_key = os.getenv('SECRET_KEY')
# for now
app.config['SESSION_COOKIE_NAME'] = 'mySpotifyInsight_cookie'
# oauth = OAuth(app)

@app.route("/")
def index():
    return app.send_static_file('index.html')

#FIXME: for now
if __name__ == "__main__":
    # Only for debugging while developing
    app.run(host='0.0.0.0', debug=False, port=os.environ.get('PORT', 80))

@app.route("/test")
def test_route():
    return "test route"

admin_bp = Blueprint('admin', __name__)

@admin_bp.route("/admin")
def admin():
    return "admin page"

api/blueprints/__init__.py
#do not delete this file...

api/blueprints/admin.py
from flask import Blueprint

#routes for admin related works

admin_bp = Blueprint('admin', __name__)

@admin_bp.route("/admin")
def admin():
    return "this is admin page..."

api/blueprints/auth.py
from flask import Blueprint, url_for, session, redirect, request, jsonify
import spotipy
from api.decorators import login_required
#from api.decorators import db, db_cursor
from api.utils import get_spotify_oauth, get_token_info, get_spotify_object, refresh_token_info
from api.extensions import limiter

# routes relate to authentication

auth_bp = Blueprint('auth', __name__)


@auth_bp.route("/auth/logout")
@login_required
def logout():
    session['LOGGED_IN'] = False
    return redirect('http://localhost:3000')


@auth_bp.route("/auth/login",  methods=['GET'])
def login():
    # set up the spotify authorization
    sp_oauth = get_spotify_oauth()

    # make the authorization request and return the link where can approve the request
    auth_url = sp_oauth.get_authorize_url()
    # redirect user to that link (where they can click "agree")
    return redirect(auth_url)


# the page that returns to after user get authentication from spotify
@ auth_bp.route("/auth/redirect")
def redirect_page():
    sp_oauth = get_spotify_oauth()
    session.clear()

    # get the code passed back with the query string, it's needed to get the access token
    code = request.args.get('code')

    # if no code is given, that means user chose "decline" not "agree"
    if code is None:
        try:
            del session['TOKEN_INFO']
        finally:
            # FIXME: need a page I guess
            return 'Authorization failed'

    # get token info (access token included) with the code
    token_info = sp_oauth.get_access_token(code, check_cache=False)

    # save token info into the session
    session['TOKEN_INFO'] = token_info

    # FIXME
    refresh_token_info(token_info['refresh_token'])

    # try to login the user in
    try:
        # get spotify object that we will make request of
        sp = get_spotify_object()
        cur_user = sp.current_user()
        cur_user_name = cur_user['display_name']
        cur_user_id = cur_user['id']

        # FIXME: databaseneeded

        session['LOGGED_IN'] = True
        session['USER_NAME'] = cur_user_name
        session['USER_ID'] = cur_user_id

    except Exception as e:
        print(e)

    return redirect('http://localhost:3000/home')


@ auth_bp.route("/auth/token_expired")
def token_expired():
    return "Your access token is expired, please go to login page to refresh the access token"


@ auth_bp.route("/auth/access_denied")
def access_denied():
    return "You don't have the permission for this operation"

api/blueprints/main.py
from flask import Blueprint, render_template, request, app

#routes for public (not specific to a user)

main_bp = Blueprint('main', __name__)


@main_bp.route("/")
def index():
    # return main_bp.send_static_file('index.html')
    #return "hello, this is a test page..."
    return render_template('main/site_landing_page.html')

api/blueprints/user.py
from flask import Blueprint, session
from api.decorators import login_required, token_checked

# routes for specific user (information)

user_bp = Blueprint('user', __name__)


@user_bp.route("/user/homepage")
@login_required
@token_checked
def home():
    return "this is user page..."

api/templates/main/site_landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Site Landing Page</title>
</head>
<body>
    <h1>Site Landing Page</h1>

    <h3><a href="{{url_for('auth.login') }}">Login</a></h3>

</body>
</html>

api/templates/user/dashboard_interface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DashBoard Interface</title>
</head>
<body>
    <h1> {{user_name}}'s Home Page</h1>

    <h4>Simple User Profile</h4>
    <ul>
        <li>{{user_info['user_name'] }}</li>
        <li>followers: {{user_info['num_followers'] }}</li>
        <li>following: {{user_info['user_following_num'] }}</li>
        <li>saved songs: {{user_info['user_saved_songs'] }}</li>
        <li>public playlists: {{user_info['num_public_playlists'] }}</li>
        <li>private playlists: {{user_info['num_private_playlists'] }}</li>
        <li>listening from: {{user_info['country'] }}</li>
    </ul>

    <h4>Top Artists</h4>
    <ol>
    {% for artist in user_info['top_artists'] %}
        <li><a href="{{url_for('user.artist_details', artist_id=artist['id']) }}">{{artist['name']}} </a></li>
    {% endfor %}
    </ol>



    <h4>Top Tracks</h4>
    <ol>
        {% for track in user_info['top_tracks'] %}
        <li>
            <a href="{{url_for('user.track_details', track_id=track['id']) }}">{{track['name']}}</a>
        </li>
        {% endfor %}
    </ol>



    <h4>Top Albums</h4>
    <ol>
        {% for album in user_info['top_albums'] %}
        <li>
            <a href="{{url_for('user.album_details', album_id=album['id']) }}">
                {{album['name'] }}
            </a>
        </li>
        {% endfor %}
    </ol>

    <iframe src="https://open.spotify.com"></iframe>
    <iframe src="https://www.youtube.com"></iframe>

</body>
</html>